ballonsballons-at/ballons-jaen

.env.public, .gitignore, gatsby-config.ts
=> fix: add GATSBY_ENDPOINT_URL_ORIGIN

src/components/templates/Home/LittleThingsSecton/LittleThingsSection.tsx, src/components/templates/Home/Riesges/RiesgesBottomSection.tsx
=> Fix RTF defaults in Home

src/components/organisms/BasketDrawer/BasketDrawer.tsx, src/components/organisms/BasketDrawer/CartItem.tsx, src/components/organisms/BasketDrawer/CartOrderSummary.tsx, src/components/organisms/LoginModal/LoginModal.tsx, src/components/templates/BlogOverview/BlogOverviewHero.tsx, src/components/templates/Dekoration/DekorationenHero.tsx, src/components/templates/Großhandel/AdviceSection.tsx, src/components/templates/Home/ImaginationSection/ImaginationBottomSection.tsx, src/components/templates/Home/LittleThingsSecton/LittleThingsSection.tsx, src/components/templates/Home/Riesges/Riesges.tsx, src/components/templates/Home/Riesges/RiesgesBottomSection.tsx, src/components/templates/ProductTemplate/ProductTemplate.tsx, src/components/templates/ProductsTemplate/ProductsPageShell.tsx
**Checklist:**
-   [x] Have you added an explanation of what your changes do and why you'd like them to be included?
-   [ ] Have you updated or added documentation for the change?
-   [x] Have you tested your changes with successful results?
**Type of Changes:**
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Documentation (non-breaking change which adds documentation)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
**What is the new behavior (if this is a feature change)?**
- The product page overflow has been fixed for some mobile devices.
- The spacing of some sections has been improved throughout the entire homepage.
- The shop footer has been improved.
- …
=> feat: improve spacing and sizing

src/components/CardWithImageBackground.tsx, src/components/fields/CardWithImageBackgroundField.tsx, src/components/templates/Home/HeartSection/HeartRightSection.tsx, src/components/templates/Home/LittleThingsSecton/LittleThingsSection.tsx, src/components/templates/Home/NewsSection/NewsSection.tsx, src/components/templates/Home/Riesges/RiesgesTopSection.tsx
- Add fixed size to news section image
- Add min card width to CardWithImageBackground and CardWithImageBackgroundField
- Fix Riesges section responsiveness
- Fix overflow issue in the LittleThings section
- Improve Heart section card grid
=> Add responsiveness improvements

src/components/molecules/ParallaxBackground/ParallaxBackground.tsx, src/components/templates/HomeTemplate/Hero/Hero.tsx
=> feat: center hero text

src/components/templates/HomeTemplate/Hero/Hero.tsx
=> feat: add safari support for hero

src/components/molecules/ParallaxBackground/ParallaxBackground.tsx
=> feat: remove hero ballons for mobile

src/components/fields/LinkButtonField.tsx, src/components/organisms/ContentPageSection/ContentPageSection.tsx, src/components/organisms/ContentPageSection/ConvincedSection.tsx, src/components/organisms/ConvincedSection.tsx, src/components/organisms/WhiteBoxWithDashBorder.tsx, src/components/templates/KategorieA/DekorationenHero.tsx, src/components/templates/KategorieB/ProductCatlog.tsx, src/components/templates/KategorieB/WirGestaltenPartyHero.tsx
**Changes**
1. `feat: combine text field with Chakra at KategorieA`
Updated `TextField` component in `KategorieA` to utilize `Chakra UI`, bringing the component's look and feel in line with the overall style of our application. All original functionalities are preserved during this process.
2. `feat: combine text field with Chakra at KategorieB`
Mirroring the changes in `KategorieA`, `TextField` in `KategorieB` has also been updated with `Chakra UI`, establishing UI consistency across the two components.
**Test Coverage**
Both features have been thoroughly tested to confirm no regression issues. The `TextField` components in `KategorieA` and `KategorieB` are fully functional, plus the new aesthetic improvements provided by `Chakra UI`.
Please go through the changes and share any feedback …
=> feat: combine text field with Chakra on Kategorie pages

package.json, src/common/utils.tsx, src/components/CardWithImageBackground.tsx, src/components/fields/CardWithImageBackgroundField.tsx, src/components/organisms/ContentPageSection/BallonGas.tsx, src/components/organisms/NewsSlider/WhiteDesktopSlider.tsx, src/components/organisms/NewsSlider/WhiteMobileSlider.tsx, src/components/organisms/NotificationBanner/NotificationBanner.tsx, src/components/templates/BlogOverview/BlogCard.tsx, src/components/templates/BlogOverview/BlogOverview.tsx, src/components/templates/BlogOverview/BlogOverviewHero.tsx, src/components/templates/BlogOverview/BlogsSection.tsx, src/components/templates/BlogPage/BlogMeta.tsx, src/components/templates/BlogPage/BlogPage.tsx, src/components/templates/BlogPage/BlogPageHero.tsx, src/components/templates/BlogPage/BlogPageSection.tsx, src/components/templates/BlogPage/BlogSlider.tsx, src/components/templates/BlogPage/BlogTags.tsx, src/components/templates/Contact/Contact.tsx, src/components/templates/Contact/ContactBottomSection.tsx, src/components/templates/Contact/ContactHero.tsx, src/components/templates/Contact/ContactTimings.tsx, src/components/templates/Faq/FaqBallons.tsx, src/components/templates/Faq/FaqQuestionAnswer.tsx, src/components/templates/Faq/HeroFaq.tsx, src/components/templates/Imprint/Imprint.tsx, yarn.lock
This pull request introduces several updates where Chakra UI has been integrated with the TextField component in different sections of the application. This aims to improve the overall user experience, making our platform more intuitive and engaging. Here's a brief overview of the commits:
- **Commit: `feat: combine text field with Chakra at Imprint`**  
This commit integrates the Chakra UI with the TextField in the Imprint section, enhancing its visual appeal and interactivity.
- **Commit: `feat: combine text field with Chakra at Contact`**  
Similar enhancements were made to the Contact section where the TextField now uses Chakra UI. This improves the responsiveness and usability of the form in this section.
- **Commit: `feat: combine text field with Chakra at Blog`**  
The TextField in …
=> feat: combine TextField with Chakra UI in Multiple Sections

src/components/templates/AboutUs/AboutBallons.tsx, src/components/templates/AboutUs/AboutHeroSection.tsx, src/components/templates/AboutUs/AboutUs.tsx, src/components/templates/AboutUs/OurCustomers.tsx, src/components/templates/AboutUs/OurTeam/OurBoss.tsx, src/components/templates/AboutUs/OurTeam/OurTeam.tsx, src/components/templates/AboutUs/OurTeam/TeamMember.tsx, src/components/templates/Contact/Contact.tsx, src/components/templates/ContactAboutUs/ContactAboutUs.tsx, src/components/templates/KategorieB/ProductCatlog.tsx, src/pages/kontakt.tsx, src/styles/global.css
Contact and AboutUs page still WIP
=> feat: improve editing

src/components/templates/BlogPage/BlogPageSection.tsx
This PR centralizes the TextBlockSection on the Blog Page,
enhancing readability and improving visual balance of the content.
This change aligns with the website's overall design aesthetic,
focusing on a clean and organized appearance.
=> feat: align TextBlockSection to Center on Blog

src/components/organisms/ContentPageSection/ContentPageSection.tsx, src/components/templates/BlogPage/BlogSlider.tsx, src/components/templates/HomeTemplate/NewsSection/NewsSection.tsx, src/components/templates/KategorieB/ProductCatlog.tsx, src/components/templates/KategorieB/WirGestaltenPartyHero.tsx
This PR introduces a series of UI and UX enhancements aiming to improve the overall experience on our website. Detailed changes are as follows:
**Features**
- Converted the 1x9 image grid to a more visually appealing and balanced 3x3 grid, enhancing the visual layout of the site.
- Added lightbox functionality to the KategorieB Hero and Product Catalog sections. Users will now be able to see enlarged images upon clicking, offering a more immersive viewing experience.
- Implemented larger border radius to the News Section, providing a more modern and smooth design aesthetic.
- Increased the slider image size, enabling users to better view details in the slider images.
**Bug Fixes**
- Corrected the heading background in the Category Content Section, ensuring consistency across all headings …
=> Improve Website UX and UI

src/components/organisms/ContentPageSection/BallonGas.tsx, src/components/organisms/ContentPageSection/ContentPageSection.tsx, src/components/organisms/WhiteBoxWithDashBorder.tsx, src/components/templates/Contact/ContactTimings.tsx, src/components/templates/HomeTemplate/ImaginationSection/ImaginationUpperSection.tsx, src/components/templates/HomeTemplate/NewsSection/NewsContent.tsx, src/components/templates/KategorieA/DekorationenHero.tsx
=> feat: remove text variant in TextField

src/common/utils.tsx, src/components/organisms/ContentPageSection/ContentPageSection.tsx, src/components/templates/Contact/ContactTimings.tsx
This pull request includes two new features:
A utility function that removes HTML tags from a string.
Removal of the "variant" option on the Text Field component.
=> feat: remove variant and html for TOC

src/common/assets/Ballon.tsx, src/common/assets/Logo.tsx, src/common/assets/Skyline.tsx, src/components/Navigation/MobileHamburger.tsx, src/components/Navigation/NavAuthButton.tsx, src/components/Navigation/Navbar.tsx, src/components/molecules/BallonButton/BallonButton.tsx, src/components/molecules/ParallaxBackground/style.ts, src/components/molecules/ParallaxHero/style.ts, src/components/molecules/Searchbar/Searchbar.tsx, src/components/molecules/SideButtons/SideButtons.tsx, src/components/organisms/BasketDrawer/BasketDrawer.tsx, src/components/organisms/ContentPageSection/ContentPageSection.tsx, src/components/templates/ProductTemplate/ProductTemplate.tsx, src/components/templates/ProductsTemplate/ProductsPageShell.tsx, src/components/templates/ProductsTemplate/ProductsTemplate.tsx, src/components/templates/WissenPage/BlogsSection.tsx, src/styles/global.css
=> Feat: add minor improvements to the design

src/common/assets/joy.inline.svg, src/components/CardWithImageBackground.tsx, src/components/molecules/ParallaxBackground/BallonSvg.tsx, src/components/molecules/ParallaxBackground/ParallaxBackground.tsx, src/components/molecules/ParallaxBackground/style.ts, src/components/molecules/ParallaxHero/ParallaxHero.tsx, src/components/templates/HomeTemplate/JoySection/JoySection.tsx
=> feat: add svg events

src/common/assets/joy.inline.svg, src/components/hooks/scroll.ts, src/components/molecules/ParallaxBackground/BallonSvg.tsx, src/components/molecules/ParallaxBackground/ParallaxBackground.tsx, src/components/molecules/ParallaxHero/MobileHero.tsx, src/components/molecules/ParallaxHero/ParallaxHero.tsx, src/components/templates/HomeTemplate/JoySection/JoySection.tsx
=> Feat: add and adjust scroll hook

src/components/molecules/ProductSlider/ProductSlider.tsx, src/components/templates/HomeTemplate/FeaturedProductsSection/FeaturedProductsSection.tsx, src/components/templates/HomeTemplate/Riesges/RiesgesBottomSection.tsx
=> Feat: improve the mobile featured products section

src/components/molecules/ParallaxHero/ParallaxHero.tsx
=> Feat: white bg for hero btn

src/components/Footer/BottomFooter.tsx
=> Feat: add whitespace to bottom footer
